### Health
GET http://localhost:8080/api/v1/health

### Swagger docs
GET http://localhost:8080/v3/api-docs

### Sign in
POST http://localhost:8080/api/v1/authentication/sign-in
Content-Type: application/json

{
  "usernameOrEmail": "maria.lopez@movisafe.pe",
  "password": "Demo1234"
}

### Get all routes
GET http://localhost:8080/api/v1/routes

### Get tracking events
GET http://localhost:8080/api/v1/real-time-tracking
